### PR TITLE
added a component of giving a brief description of the vibe

### PR DESCRIPTION
**Pull request by adeldelvalle**

### CODE REVIEW

**Review by khamseaffan — APPROVED** [review]
LGTM

**Comment by khamseaffan** [comment]
build is failing so I have  dismissed my review, 
BTW the second commit by me on this PR is due to merging conflict that I have resolved now

**Comment by BoyanXu** [comment]
The test database is fast to create and delete. I think the problem is I should prevent the Travis from prompting interactive choices.

**Comment by BoyanXu** [comment]
I suggest we accept the PR first. I can merge my fix then.

**Review by khamseaffan — APPROVED** [review]
LGTM

**Review by yp2353 — APPROVED** [review]

**Pull request merged**
